Adds TC Scoring From Contested Possession
robocup-ssl-br/rules-technical-challenge-regular pull request #1
Opened 2024-04-29 12:39 UTC by JoaoVictor0508

This Technical Challenge aims at the dribbler component development of the SSL Regular League robots. Besides, the TC also plans the use of passes to improve team coordination. The challenge mixes the rules of the 1 and 2 Hardware Challenges of RoboCup Online 2021.

2024-04-30 18:26 UTC, ersaraujo approved these changes
LGTM 👍🏽

2024-05-01 22:47 UTC, PedroPizarro commented on 2024/2024-ssl-dribbler-rules.adoc
> +. Up to **3** robots of the team are placed on the middle line.
Sugiro mencionar que o trial acaba se for gol ou fora, como estão nas regras.

2024-05-01 22:47 UTC, PedroPizarro commented on 2024/2024-ssl-dribbler-rules.adoc
> +. Every team has to perform the three trials of each scenario, or can withdrawn a trial, counting 20s.
@ersaraujo  @JoaoVictor0508  Não lembro o que a gente definiu, os cenários ficaram que iam ser definidos no dia ou que ia ser um misto de soltarmos o cenário agora com algo aleatório depois? Em ambos os casos sugiro da gente comentar como os cenários vão ser definidos e quando aqui nas regras.

2024-05-01 22:47 UTC, PedroPizarro commented on 2024/2024-ssl-dribbler-rules.adoc
> += RoboCup Brasil 2024 SSL Scoring from contested possession
@JoaoVictor0508 Sugiro colocar Brasil com z já que é um documento em inglês

2024-05-05 12:35 UTC, JoaoVictor0508 commented on 2024/2024-ssl-dribbler-rules.adoc
> +. Up to **3** robots of the team are placed on the middle line.
I commented this on the Rules section.

2024-05-19 23:53 UTC, PedroPizarro requested changes
Waiting for the scenarios for approval.

2026-06-02 23:22 UTC, closed without merging